<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link rel="stylesheet" href="css/header.css">
    <link rel="stylesheet" href="css/general.css">
</head>

<body>
    <header class="header">
        <div class="header_ribbon"></div>
        <p class="header_p-iromo">Livraison offerte à partir de 65 &euro;d'achat !</p>
        
        <div class="conteneur">
            <div class="header_div-init">
                <img clas="header_logo" src="img/logo.png" alt="logo Cup og tea">
                <div class="header_div-basket">
                    <a class="header_div-basket-name"href="" >Mon panier</a>
<a href="" class="fas fa-shopping-cart header_div-basket-icon"></a>
                    <a class="header_div-basket-price" href="" id="headerTotalPrice">JS</a>
                </div>
            </div>
            <nav class="header_navbar">
                <a href="">Thés</a>
                <a href="">Grand crus</a>
                <a href="">Accessoires</a>
                <a href="">Epicerie</a>
                <a href="">Notre histoire</a>
            </nav>
        </div>
    </header>
